version: '3.9'
services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql_stakeholder-env-trial
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
  redis:
    image: redis:6.2.6-alpine3.15
    container_name: redis_stakeholder-env-trial
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379